### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by simonsmith** [suitcss/base#25]
Waiting on npm access. Will address #21

**Comment by simonsmith** [comment]
@necolas `npm owner ls` still lists yourself. Do you need to add us all to each package?

**Comment by necolas** [comment]
I added you to suit, utils, and components. figured these smaller packages were moving to the monorepo. should i add you to each one?

**Comment by necolas** [comment]
added you all to 'base'

**Comment by simonsmith** [comment]
I thought that each package would remain the same on npm, so perhaps we do need to be added to each one.

**Comment by simonsmith** [comment]
Done https://github.com/suitcss/base/releases/tag/1.0.0

**Comment by giuseppeg** [comment]
<blockquote>I thought that each package would remain the same on npm, so perhaps we do need to be added to each one.</blockquote>

Yeah that's still not clear to me. @necolas was your original idea to develop in the monorepo and publish base, components and utils (the bundles) only?

**Comment by necolas** [comment]
oh i see, yeah so you can still publish to each existing package. forgot about that. you should be owners of all the repos now.
